apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
  labels:
    app: {{ include "petclinic.name" . }}
type: Opaque
stringData:
  db-username: {{ .Values.mysql.auth.username | quote }}
  db-password: {{ .Values.mysql.auth.password | quote }}
